sudo: required
services:
  - docker
  
before_install:
  - docker build -t anirban1980/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true anirban1980/docker-react  npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-test-1"
  env: "DockerTest1-env"
  bucket_name: "elasticbeanstalk-ap-south-1-403065120601"
  bucket_path: "docker-test-1"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
